.\" Copyright (c) 2010 Ben Harris
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd April 23, 2010
.Dt AUND.PASSWD 5
.Sh NAME
.Nm aund.passwd
.Nd user database for
.Xr aund 8
.Sh DESCRIPTION
.Xr aund 8
has its own password database, held in a file designated by
.Xr aund.conf 5 .
Each line of the file defines one user, and consists of from two to
four fields, separated by colon
.Pq Ql \&:
characters.
.Pp
The fields are:
.Pp
.Bl -enum -compact
.It
Login name
.It
Encrypted password
.It
Users home directory
.It
Optional boot option
.It
Priviledge Flag
.El
.Pp
Note for users outside the root directory the dot(.) must be replaced by (/)
.Pp
The password is encrypted using
.Xr crypt 3 ,
and the boot option is described under the
.Ic opt4
directive in
.Xr aund.conf 5 .
.Sh SEE ALSO
.Xr crypt 3 ,
.Xr aund.conf 5 ,
.Xr aund 8
