#line 2 "conf_lex.c"

#line 4 "conf_lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cfy_create_buffer
#define yy_delete_buffer cfy_delete_buffer
#define yy_flex_debug cfy_flex_debug
#define yy_init_buffer cfy_init_buffer
#define yy_flush_buffer cfy_flush_buffer
#define yy_load_buffer_state cfy_load_buffer_state
#define yy_switch_to_buffer cfy_switch_to_buffer
#define yyin cfyin
#define yyleng cfyleng
#define yylex cfylex
#define yylineno cfylineno
#define yyout cfyout
#define yyrestart cfyrestart
#define yytext cfytext
#define yywrap cfywrap
#define yyalloc cfyalloc
#define yyrealloc cfyrealloc
#define yyfree cfyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cfyrestart(cfyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int cfyleng;

extern FILE *cfyin, *cfyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cfytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cfytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cfyrestart()), so that the user can continue scanning by
	 * just pointing cfyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cfytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int cfyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow cfywrap()'s to do buffer switches
 * instead of setting up a fresh cfyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void cfyrestart (FILE *input_file  );
void cfy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cfy_create_buffer (FILE *file,int size  );
void cfy_delete_buffer (YY_BUFFER_STATE b  );
void cfy_flush_buffer (YY_BUFFER_STATE b  );
void cfypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void cfypop_buffer_state (void );

static void cfyensure_buffer_stack (void );
static void cfy_load_buffer_state (void );
static void cfy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cfy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cfy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cfy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cfy_scan_bytes (yyconst char *bytes,int len  );

void *cfyalloc (yy_size_t  );
void *cfyrealloc (void *,yy_size_t  );
void cfyfree (void *  );

#define yy_new_buffer cfy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cfyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cfy_create_buffer(cfyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cfyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cfy_create_buffer(cfyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cfywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *cfyin = (FILE *) 0, *cfyout = (FILE *) 0;

typedef int yy_state_type;

extern int cfylineno;

int cfylineno = 1;

extern char *cfytext;
#define yytext_ptr cfytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cfytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	cfyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 32
#define YY_END_OF_BUFFER 33
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[165] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       33,   31,    3,    2,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,    3,   31,    0,    2,   31,
        0,   30,    1,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   29,   31,
       28,   31,   31,   30,   31,   31,   31,    8,   31,   31,
       31,   31,   31,   31,   31,    9,   31,   31,   31,   31,

       23,   21,   22,   31,   25,   24,   31,   27,   31,   31,
       31,   31,   31,   31,   11,   31,    7,   31,   31,   31,
       31,   31,   16,   17,   18,   20,   26,   31,   31,    5,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       13,   31,   31,   31,   10,   31,    6,   31,   31,   31,
       14,   31,    8,   31,   12,    4,   19,   31,   31,   31,
       31,   31,   15,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    5,    1,
        1,    1,    1,    1,    6,    1,    1,    1,    1,    1,
        1,    7,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    8,    1,    1,    6,    1,    9,   10,   11,   12,

       13,   14,   15,   16,   17,    1,   18,   19,   20,   21,
       22,   23,    1,   24,   25,   26,   27,    1,   28,    1,
       29,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[30] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[170] =
    {   0,
        0,    0,   20,    0,   28,   29,   46,    0,   61,   77,
      208,    0,  205,  209,   31,   33,  203,  192,  191,  182,
      185,  178,  172,  177,   39,   44,  174,  184,  187,  182,
      165,  174,  176,  174,  173,  168,  175,  165,  170,  176,
      162,   45,  159,  169,    0,  179,   60,  177,  209,   62,
      174,  173,  209,  164,  166,  161,  164,  147,  158,  149,
      156,  144,  148,  144,  154,  151,  144,  139,  139,  143,
      136,  135,  144,  139,  141,  144,  128,  134,    0,  138,
        0,  124,  125,  144,  138,  120,  124,  121,  137,  126,
      116,  128,  121,  126,  125,    0,  128,  123,  115,  121,

        0,    0,    0,  111,    0,    0,  114,    0,  106,  117,
      116,  113,   63,  118,    0,  107,    0,   70,  103,  102,
      103,   95,    0,    0,    0,    0,    0,  108,  100,    0,
      105,   58,   94,  104,   89,   95,   87,   74,   91,   78,
        0,   70,   71,   65,    0,   72,    0,   66,   66,   62,
        0,   65,    0,   72,    0,    0,    0,   72,   60,   46,
       40,   11,    0,  209,   30,  106,  109,  111,  114
    } ;

static yyconst flex_int16_t yy_def[170] =
    {   0,
      164,    1,    1,    3,    3,    3,    3,    7,    3,    3,
      164,  165,  164,  164,  166,  167,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  164,  166,  168,  164,  167,
      169,  165,  164,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  164,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,

      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,    0,  164,  164,  164,  164,  164
    } ;

static yyconst flex_int16_t yy_nxt[239] =
    {   0,
       12,   13,   14,   15,   16,   12,   12,   17,   12,   18,
       12,   19,   12,   12,   12,   12,   20,   12,   21,   12,
       12,   22,   23,   24,   25,   26,   27,   12,   12,   12,
       45,   12,   48,   49,   51,  163,   12,   52,   12,   28,
       28,   12,   12,   12,   12,   12,   12,   61,   29,   29,
       30,   30,  162,   31,   31,   32,   33,   34,   80,   35,
       63,   48,   49,   51,   36,   81,   52,   62,  131,   37,
       38,  151,   64,   39,   40,  135,  132,  142,  161,  143,
      160,   41,   42,  159,  158,  136,   43,  157,  156,   44,
       40,  155,  154,  153,  152,  151,  150,   41,   42,  149,

      148,  147,   43,  146,  136,   44,   47,   47,   47,   50,
       50,   48,   48,   48,   51,   51,  145,  144,  132,  141,
       79,  140,  139,  138,  137,  134,  133,  130,  129,   81,
      128,  127,  126,  125,  124,  123,  122,  121,  120,  119,
      118,  117,  116,  115,  114,  113,  112,  111,   51,   81,
      110,   79,  109,  108,  107,  106,  105,  104,  103,  102,
      101,  100,   99,   98,   97,   96,   95,   94,   93,   92,
       91,   90,   89,   88,   87,   86,   85,   50,   84,   49,
       46,   83,   82,   79,   78,   77,   76,   75,   74,   73,
       72,   71,   70,   69,   68,   67,   66,   65,   60,   59,

       58,   57,   56,   55,   54,   53,   46,  164,   11,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164
    } ;

static yyconst flex_int16_t yy_chk[239] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
      165,    3,   15,   15,   16,  162,    3,   16,    3,    5,
        6,    3,    3,    3,    3,    3,    3,   25,    5,    6,
        5,    6,  161,    5,    6,    7,    7,    7,   42,    7,
       26,   47,   47,   50,    7,   42,   50,   25,  113,    7,
        7,  160,   26,    7,    9,  118,  113,  132,  159,  132,
      158,    9,    9,  154,  152,  118,    9,  150,  149,    9,
       10,  148,  146,  144,  143,  142,  140,   10,   10,  139,

      138,  137,   10,  136,  135,   10,  166,  166,  166,  167,
      167,  168,  168,  168,  169,  169,  134,  133,  131,  129,
      128,  122,  121,  120,  119,  116,  114,  112,  111,  110,
      109,  107,  104,  100,   99,   98,   97,   95,   94,   93,
       92,   91,   90,   89,   88,   87,   86,   85,   84,   83,
       82,   80,   78,   77,   76,   75,   74,   73,   72,   71,
       70,   69,   68,   67,   66,   65,   64,   63,   62,   61,
       60,   59,   58,   57,   56,   55,   54,   52,   51,   48,
       46,   44,   43,   41,   40,   39,   38,   37,   36,   35,
       34,   33,   32,   31,   30,   29,   28,   27,   24,   23,

       22,   21,   20,   19,   18,   17,   13,   11,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cfy_flex_debug;
int cfy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cfytext;
#line 1 "conf_lex.l"
/* -*- fundamental -*- */
/*-
 * Copyright (c) 2010 Simon Tatham
 * Copyright (c) 1998, 2010 Ben Harris
 * Copyright (c) 2010 James Woodcock
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * This is part of aund, an implementation of Acorn Universal
 * Networking for Unix.
 */	
/*
 * conf_lex.l - lexer for configuration files.
 */
#line 42 "conf_lex.l"
#include <sys/types.h>
#include <sys/stat.h>

#include <err.h>
#include <string.h>
#include <assert.h>

#include "extern.h"
#include "fileserver.h"

#ifndef S_IFIFO
#define S_IFIFO 0
#endif
#ifndef S_IFCHR
#define S_IFCHR 0
#endif
#ifndef S_IFDIR
#define S_IFDIR 0
#endif
#ifndef S_IFDIR
#define S_IFDIR 0
#endif
#ifndef S_IFBLK
#define S_IFBLK 0
#endif
#ifndef S_IFREG
#define S_IFREG 0
#endif
#ifndef S_IFLNK
#define S_IFLNK 0
#endif
#ifndef S_IFSOCK
#define S_IFSOCK 0
#endif
#ifndef S_IFWHT
#define S_IFWHT 0
#endif

#define CF_EOF 0
#define CF_FUNC 1
#define CF_BOOLEAN 2
#define CF_WORD 3
#define CF_NEWLINE 4

static void conf_read_file(const char *);

union cfything {
	int boolean;
	struct {
		void (*func)(union cfything *);
		mode_t mode;
	} func;
};

static void conf_cmd_debug(union cfything *);
static void conf_cmd_syslog(union cfything *);
static void conf_cmd_root(union cfything *);
static void conf_cmd_urd(union cfything *);
static void conf_cmd_pwfile(union cfything *);
static void conf_cmd_lib(union cfything *);
static void conf_cmd_beebem(union cfything *);
static void conf_cmd_infofmt(union cfything *);
static void conf_cmd_safehandles(union cfything *);
static void conf_cmd_opt4(union cfything *);
static void conf_cmd_timeout(union cfything *);
static void conf_cmd_typemap_name(union cfything *);
static void conf_cmd_typemap_perm(union cfything *);
static void conf_cmd_typemap_type(union cfything *);
static void conf_cmd_typemap_default(union cfything *);

static void dequote(char *);
	
static int cfylex(int start, union cfything *thing);

static int cfy_line;

#define YY_DECL static int cfylex(int start, union cfything *thing)





#line 703 "conf_lex.c"

#define INITIAL 0
#define BORING 1
#define TYPEMAP 2
#define TYPEMAP_TYPE 3
#define BOOLEAN 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cfylex_destroy (void );

int cfyget_debug (void );

void cfyset_debug (int debug_flag  );

YY_EXTRA_TYPE cfyget_extra (void );

void cfyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *cfyget_in (void );

void cfyset_in  (FILE * in_str  );

FILE *cfyget_out (void );

void cfyset_out  (FILE * out_str  );

int cfyget_leng (void );

char *cfyget_text (void );

int cfyget_lineno (void );

void cfyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cfywrap (void );
#else
extern int cfywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( cfytext, cfyleng, 1, cfyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( cfyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( cfyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, cfyin))==0 && ferror(cfyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(cfyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cfylex (void);

#define YY_DECL int cfylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cfytext and cfyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 127 "conf_lex.l"


	if (start != -1) BEGIN(start);

 /* Backslash-escaped newline is completely ignored */
#line 900 "conf_lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! cfyin )
			cfyin = stdin;

		if ( ! cfyout )
			cfyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cfyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cfy_create_buffer(cfyin,YY_BUF_SIZE );
		}

		cfy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cfytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 165 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 209 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 132 "conf_lex.l"
cfy_line++;
	YY_BREAK
/* Newline, with optional comment before it. Ignored in INITIAL state;
  * otherwise returned as a token so that commands can detect premature
  * running-out-of-arguments. */
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 137 "conf_lex.l"
cfy_line++; if (YY_START != INITIAL) { BEGIN(INITIAL); return CF_NEWLINE; }
	YY_BREAK
/* Ignore whitespace except insofar as it splits words */
case 3:
YY_RULE_SETUP
#line 140 "conf_lex.l"
/* do nothing */
	YY_BREAK
/* In starting state, recognise main config keywords, return them as
  * function pointers, and switch into BORING state so that subsequent
  * words will be returned as CF_WORD. */

case 4:
YY_RULE_SETUP
#line 146 "conf_lex.l"
BEGIN(TYPEMAP);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 147 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_debug; return CF_FUNC;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 148 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_syslog; return CF_FUNC;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 149 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_root; return CF_FUNC;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 150 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_lib; return CF_FUNC;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 151 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_urd; return CF_FUNC;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 152 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_pwfile; return CF_FUNC;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 153 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_opt4; return CF_FUNC;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 154 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_timeout; return CF_FUNC;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 155 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_beebem; return CF_FUNC;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 156 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_infofmt; return CF_FUNC;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 157 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_safehandles; return CF_FUNC;
	YY_BREAK


case 16:
YY_RULE_SETUP
#line 160 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_typemap_name; return CF_FUNC;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 161 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_typemap_perm; return CF_FUNC;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 162 "conf_lex.l"
BEGIN(TYPEMAP_TYPE);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 163 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_typemap_default; return CF_FUNC;
	YY_BREAK


case 20:
YY_RULE_SETUP
#line 166 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_typemap_type; thing->func.mode = S_IFIFO; return CF_FUNC;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 167 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_typemap_type; thing->func.mode = S_IFCHR; return CF_FUNC;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 168 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_typemap_type; thing->func.mode = S_IFDIR; return CF_FUNC;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 169 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_typemap_type; thing->func.mode = S_IFBLK; return CF_FUNC;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 170 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_typemap_type; thing->func.mode = S_IFREG; return CF_FUNC;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 171 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_typemap_type; thing->func.mode = S_IFLNK; return CF_FUNC;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 172 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_typemap_type; thing->func.mode = S_IFSOCK; return CF_FUNC;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 173 "conf_lex.l"
BEGIN(BORING); thing->func.func = conf_cmd_typemap_type; thing->func.mode = S_IFWHT; return CF_FUNC;
	YY_BREAK


case 28:
YY_RULE_SETUP
#line 176 "conf_lex.l"
*(int *)thing = 1; BEGIN(BORING); return CF_BOOLEAN;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 177 "conf_lex.l"
*(int *)thing = 0; BEGIN(BORING); return CF_BOOLEAN;
	YY_BREAK

/* Any word without a specific meaning from context is returned as CF_WORD. */
case 30:
YY_RULE_SETUP
#line 181 "conf_lex.l"
dequote(cfytext); return CF_WORD; /* [deconfuse jed syntax highlighting: '] */
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 182 "conf_lex.l"
return CF_WORD;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BORING):
case YY_STATE_EOF(TYPEMAP):
case YY_STATE_EOF(TYPEMAP_TYPE):
case YY_STATE_EOF(BOOLEAN):
#line 183 "conf_lex.l"
return CF_EOF;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 185 "conf_lex.l"
ECHO;
	YY_BREAK
#line 1169 "conf_lex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed cfyin at a new source and called
			 * cfylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = cfyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( cfywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cfytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cfylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cfyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cfyrestart(cfyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cfyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 165 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 165 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 164);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up cfytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cfyrestart(cfyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cfywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cfytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cfyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        cfyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cfy_create_buffer(cfyin,YY_BUF_SIZE );
	}

	cfy_init_buffer(YY_CURRENT_BUFFER,input_file );
	cfy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cfy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cfypop_buffer_state();
	 *		cfypush_buffer_state(new_buffer);
     */
	cfyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cfy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (cfywrap()) processing, but the only time this flag
	 * is looked at is after cfywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void cfy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	cfyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cfy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cfyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cfy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cfyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cfy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	cfy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cfy_create_buffer()
 * 
 */
    void cfy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cfyfree((void *) b->yy_ch_buf  );

	cfyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cfyrestart() or at EOF.
 */
    static void cfy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cfy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cfy_init_buffer was _probably_
     * called from cfyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void cfy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cfy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void cfypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	cfyensure_buffer_stack();

	/* This block is copied from cfy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cfy_switch_to_buffer. */
	cfy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void cfypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cfy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cfy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cfyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)cfyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cfyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)cfyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cfyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cfy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cfyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cfy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cfy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cfylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cfy_scan_bytes() instead.
 */
YY_BUFFER_STATE cfy_scan_string (yyconst char * yystr )
{
    
	return cfy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cfylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cfy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cfyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cfy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cfy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cfy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cfytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cfytext[cfyleng] = (yy_hold_char); \
		(yy_c_buf_p) = cfytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		cfyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int cfyget_lineno  (void)
{
        
    return cfylineno;
}

/** Get the input stream.
 * 
 */
FILE *cfyget_in  (void)
{
        return cfyin;
}

/** Get the output stream.
 * 
 */
FILE *cfyget_out  (void)
{
        return cfyout;
}

/** Get the length of the current token.
 * 
 */
int cfyget_leng  (void)
{
        return cfyleng;
}

/** Get the current token.
 * 
 */

char *cfyget_text  (void)
{
        return cfytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void cfyset_lineno (int  line_number )
{
    
    cfylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see cfy_switch_to_buffer
 */
void cfyset_in (FILE *  in_str )
{
        cfyin = in_str ;
}

void cfyset_out (FILE *  out_str )
{
        cfyout = out_str ;
}

int cfyget_debug  (void)
{
        return cfy_flex_debug;
}

void cfyset_debug (int  bdebug )
{
        cfy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cfylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    cfyin = stdin;
    cfyout = stdout;
#else
    cfyin = (FILE *) 0;
    cfyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cfylex_init()
     */
    return 0;
}

/* cfylex_destroy is for both reentrant and non-reentrant scanners. */
int cfylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cfy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cfypop_buffer_state();
	}

	/* Destroy the stack itself. */
	cfyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cfylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cfyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *cfyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cfyfree (void * ptr )
{
	free( (char *) ptr );	/* see cfyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 185 "conf_lex.l"



void
conf_init(const char *path)
{

	conf_read_file(path);
}

static void
conf_read_file(const char *path)
{
        FILE *f;
	union cfything thing;
	int tok, nl;

	f = fopen(path, "r");
	if (f == NULL) err(1, "%s", path);
	cfyin = f;
	cfy_line = 1;
	while ((tok = cfylex(-1, &thing)) != CF_EOF) {
		switch (tok) {
		    case CF_FUNC:
			/*
			 * Call the specified config subfunction,
			 * which will call cfylex again in states
			 * other than INITIAL. It won't
			 * automatically reset the state to INITIAL,
			 * though: that'll only happen if a newline
			 * is parsed. So subfunctions can safely
			 * just eat a fixed number of arguments, in
			 * which case we'll come back here still in
			 * BORING state and any further words on the
			 * same line will be treated as syntax
			 * errors; alternatively, a subfunction can
			 * keep retrieving tokens until it sees
			 * CF_NEWLINE, in which case we'll come back
			 * here in INITIAL state and be ready to
			 * parse the next directive.
			 */
			thing.func.func(&thing);
			break;
		    case CF_WORD:
			errx(1, "%s:%d: Syntax error: '%s'", path, cfy_line,
			     cfytext);
			break;
		}
	}
	fclose(f);
}

static void
dequote(char *str)
{
	/*
	 * Given a string starting and ending with a single quote,
	 * strip the quotes off, and reduce doubled quotes in the
	 * middle of it. This is applied to any single-quoted
	 * CF_WORD.
	 */
	char *p = str;
	assert(*str == '\'');
	str++;
	while (1) {
		if (*str == '\'' && str[1] == '\'') {
			*p++ = '\'';
			str += 2;
		} else if (*str && *str != '\'') {
			*p++ = *str++;
		} else
			break;
	}
	assert(*str == '\'' && !str[1]);
	*p = '\0';
}

static void
conf_cmd_debug(union cfything *xthing)
{
	union cfything thing;
	if (cfylex(BOOLEAN, &thing) != CF_BOOLEAN)
		errx(1, "no boolean for debug");
	debug = thing.boolean;
}

static void
conf_cmd_syslog(union cfything *xthing)
{
	union cfything thing;
	if (cfylex(BOOLEAN, &thing) != CF_BOOLEAN)
		errx(1, "no boolean for syslog");
	using_syslog = thing.boolean;
}

static void
conf_cmd_root(union cfything *thing)
{

	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no root specified");
	root = malloc(cfyleng + 1);
	strcpy(root, cfytext);
}

static void
conf_cmd_urd(union cfything *thing)
{

	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no urd specified");
	fixedurd = malloc(cfyleng + 1);
	strcpy(fixedurd, cfytext);
}

static void
conf_cmd_pwfile(union cfything *thing)
{

	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no password file specified");
	pwfile = malloc(cfyleng + 1);
	strcpy(pwfile, cfytext);
}

static void
conf_cmd_lib(union cfything *thing)
{

	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no library specified");
	lib = malloc(cfyleng + 1);
	strcpy(lib, cfytext);
}

static void
conf_cmd_beebem(union cfything *thing)
{
	int ret;

	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no beebem configuration file specified");
	beebem_cfg_file = malloc(cfyleng + 1);
	strcpy(beebem_cfg_file, cfytext);

	while ((ret = cfylex(BORING, NULL)) == CF_WORD) {
		if (!strcasecmp(cfytext, "ingress"))
			beebem_ingress = 1;
		else if (!strcasecmp(cfytext, "noingress"))
			beebem_ingress = 0;
		else
			errx(1, "unrecognised beebem option: '%s'", cfytext);
	}
}

static void
conf_cmd_infofmt(union cfything *thing)
{

	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no *INFO format keyword specified");
	if (!strcasecmp(cfytext, "riscos"))
		default_infoformat = FS_INFO_RISCOS;
	else if (!strcasecmp(cfytext, "sj"))
		default_infoformat = FS_INFO_SJ;
}

static void
conf_cmd_safehandles(union cfything *xthing)
{
	union cfything thing;
	if (cfylex(BOOLEAN, &thing) != CF_BOOLEAN)
		errx(1, "no boolean for safehandles");
	default_safehandles = thing.boolean;
}

static void
conf_cmd_opt4(union cfything *thing)
{
	char *endptr;

	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no boot option specified");
	default_opt4 = strtol(cfytext, &endptr, 0);
	if (*endptr != '\0')
		errx(1, "bad boot option");
}

static void
conf_cmd_timeout(union cfything *thing)
{
	char *endptr;

	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no timeout specified");
	default_timeout = strtol(cfytext, &endptr, 0);
	if (*endptr != '\0')
		errx(1, "bad timeout");
}

static void
conf_cmd_typemap_name(union cfything *thing)
{
	char *re;
	int type;
	
	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no re for typemap");
	re = malloc(cfyleng + 1);
	strcpy(re, cfytext);
	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no type for typemap");
	if (sscanf(cfytext, "%x", &type) != 1)
		errx(1, "bad type for typemap");
	if (fs_add_typemap_name(re, type) == -1)
		errx(1, "problem adding typemap");
}

static void
conf_cmd_typemap_perm(union cfything *thing)
{
	mode_t perm;
	int type;

	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no perm for typemap");
	if (sscanf(cfytext, "%o", &perm) != 1)
		errx(1, "bad perm for typemap");
	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no type for typemap");
	if (sscanf(cfytext, "%x", &type) != 1)
		errx(1, "bad type for typemap");
	if (fs_add_typemap_mode(perm, perm, type) == -1)
		errx(1, "problem adding typemap");
}

static void
conf_cmd_typemap_type(union cfything *thing)
{
	int type;

	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no type for typemap");
	if (sscanf(cfytext, "%x", &type) != 1)
		errx(1, "bad type for typemap");
	if (fs_add_typemap_mode(thing->func.mode, S_IFMT, type) == -1)
		errx(1, "problem adding typemap");
}

static void
conf_cmd_typemap_default(union cfything *thing)
{
	int type;

	if (cfylex(BORING, NULL) != CF_WORD)
		errx(1, "no type for typemap");
	if (sscanf(cfytext, "%x", &type) != 1)
		errx(1, "bad type for typemap");
	if (fs_add_typemap_default(type) == -1)
		errx(1, "problem adding typemap");
}

